# These are supported funding model platforms

github: grigio
custom: ["https://iris.to/techonsapevole", monero:8BxLLaFaxWUM81nniHaP9vdxTaDc5UnhTGineqJv73ERj6pegR4E58FermxUV4H3dGG3nH3XX73N99krT7koeAt86nWsk3b ]

