name: CI

on: [push, pull_request] 

jobs:

  fmt:
    runs-on: debian-12

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run clippy
      run: cargo fmt -- --check


  clippy:
    runs-on: debian-12

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      run: |
        rustup update --no-self-update stable
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy -- -D warnings


  test:
    strategy:
      matrix:
        platform: [debian-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: cargo test


  coverage:
    runs-on: debian-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cargo-tarpaulin
      run: |
        LINK="https://github.com/xd009642/tarpaulin/releases/download/0.18.0-alpha3/cargo-tarpaulin-0.18.0-alpha3-travis.tar.gz"
        curl -L --output tarpaulin.tar.gz "$LINK"
        tar -xzvf tarpaulin.tar.gz
        chmod +x cargo-tarpaulin

    - name: Run cargo-tarpaulin
      run: ./cargo-tarpaulin tarpaulin --out Xml

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3.1.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: cobertura.xml